const IDENTIFIER = '/notes/';

export const ADD_NOTE_SAGA = `${IDENTIFIER}ADD_NOTE_SAGA`;
export const ADD_NOTE = `${IDENTIFIER}ADD_NOTE`;
export const REMOVE_NOTE_SAGA = `${IDENTIFIER}REMOVE_NOTE_SAGA`;
export const REMOVE_NOTE = `${IDENTIFIER}REMOVE_NOTE`;
export const EDIT_NOTE_SAGA = `${IDENTIFIER}EDIT_NOTE_SAGA`;
export const EDIT_NOTE = `${IDENTIFIER}EDIT_NOTE`;
export const CHECKING_TAGS_SAGA = `${IDENTIFIER}CHECKING_TAGS_SAGA`;
export const CHECKING_TAGS = `${IDENTIFIER}CHECKING_TAGS`;
export const REMOVE_TAG_OF_NOTE_SAGA = `${IDENTIFIER}REMOVE_TAG_OF_NOTE_SAGA`;
export const REMOVE_TAG_OF_NOTE = `${IDENTIFIER}REMOVE_TAG_OF_NOTE`;
export const CHANGE_NOTE_VALUE = `${IDENTIFIER}CHANGE_NOTE_VALUE`;
