const IDENTIFIER = '/notes/';

export const ADD_NOTE_SAGA = `${IDENTIFIER}ADD_NOTE_SAGA`;
export const ADD_NOTE = `${IDENTIFIER}ADD_NOTE`;
export const REMOVE_NOTE_SAGA = `${IDENTIFIER}REMOVE_NOTE_SAGA`;
export const REMOVE_NOTE = `${IDENTIFIER}REMOVE_NOTE`;
export const EDIT_NOTE_SAGA = `${IDENTIFIER}EDIT_NOTE_SAGA`;
export const EDIT_NOTE = `${IDENTIFIER}EDIT_NOTE`;