const IDENTIFIER = '/tags/';

export const CHANGE_CURRENT_TAG_SAGA = `${IDENTIFIER}CHANGE_CURRENT_TAG_SAGA`;
export const CHANGE_CURRENT_TAG = `${IDENTIFIER}CHANGE_CURRENT_TAG`;
export const ADD_TAG_SAGA = `${IDENTIFIER}ADD_TAG_SAGA`;
export const ADD_TAG = `${IDENTIFIER}ADD_TAG`;
export const REMOVE_TAG_SAGA = `${IDENTIFIER}REMOVE_TAG_SAGA`;
export const REMOVE_TAG = `${IDENTIFIER}REMOVE_TAG`;
export const ADD_TAG_OF_NOTE = `${IDENTIFIER}ADD_TAG_OF_NOTE`;
export const REMOVE_TAG_OF_NOTE = `${IDENTIFIER}REMOVE_TAG_OF_NOTE`;
export const CHANGE_TAG_OF_NOTE = `${IDENTIFIER}CHANGE_TAG_OF_NOTE`;
