const IDENTIFIER = '/categories/';

export const CHANGE_CURRENT_CATEGORY = `${IDENTIFIER}CHANGE_CURRENT_CATEGORY`;
export const REMOVE_CATEGORY_SAGA = `${IDENTIFIER}REMOVE_CATEGORY_SAGA`;
export const REMOVE_CATEGORY = `${IDENTIFIER}REMOVE_CATEGORY`;
export const ADD_CATEGORY_OF_NOTE_SAGA = `${IDENTIFIER}ADD_CATEGORY_OF_NOTE_SAGA`;
export const ADD_CATEGORY_OF_NOTE = `${IDENTIFIER}ADD_CATEGORY_OF_NOTE`;
export const CHANGE_CATEGORY_OF_NOTE = `${IDENTIFIER}CHANGE_CATEGORY_OF_NOTE`;
export const ADD_CATEGORY_SAGA = `${IDENTIFIER}ADD_CATEGORY_SAGA`;
export const ADD_CATEGORY = `${IDENTIFIER}ADD_CATEGORY`;
export const REMOVE_ARR_CATEGORY_OF_NOTE = `${IDENTIFIER}REMOVE_ARR_CATEGORY_OF_NOTE`;
export const SET_CATEGORY_VALUE = `${IDENTIFIER}SET_CATEGORY_VALUE`;
export const SET_PARENT_CATEGORY = `${IDENTIFIER}SET_PARENT_CATEGORY`;
export const SET_CURRENT_CATEGORY = `${IDENTIFIER}SET_CURRENT_CATEGORY`;
export const SET_CURRENT_ID_CATEGORY = `${IDENTIFIER}SET_CURRENT_ID_CATEGORY`;
export const SET_ACTIVE_CATEGORY = `${IDENTIFIER}SET_ACTIVE_CATEGORY`;
export const ADD_CHILD_CATEGORY_SAGA = `${IDENTIFIER}ADD_CHILD_CATEGORY_SAGA`;
export const SET_ID_PARENT = `${IDENTIFIER}SET_ID_PARENT`;

