const IDENTIFIER = '/categories/';

export const CHANGE_CURRENT_CATEGORY_SAGA = `${IDENTIFIER}CHANGE_CURRENT_CATEGORY_SAGA`;
export const CHANGE_CURRENT_CATEGORY = `${IDENTIFIER}CHANGE_CURRENT_CATEGORY`;
export const REMOVE_CATEGORY_SAGA = `${IDENTIFIER}REMOVE_CATEGORY_SAGA`;
export const REMOVE_CATEGORY = `${IDENTIFIER}REMOVE_CATEGORY`;
export const ADD_CATEGORY_OF_NOTE = `${IDENTIFIER}ADD_CATEGORY_OF_NOTE`;
export const CHANGE_CATEGORY_OF_NOTE = `${IDENTIFIER}CHANGE_CATEGORY_OF_NOTE`;
export const ADD_CATEGORY_SAGA = `${IDENTIFIER}ADD_CATEGORY_SAGA`;
export const ADD_CATEGORY = `${IDENTIFIER}ADD_CATEGORY`;
